spring:
  cloud:
    gateway:
      routes:
        - id: product-route
          uri: lb://product-ms
          predicates:
            - Path=/api/v1/products/**
        - id: shoppingcart-route
          uri: lb://shoppingcart-ms
          predicates:
            - Path=/api/v1/cart/**
        - id: order-route
          uri: lb://order-ms
          predicates:
            - Path=/api/v1/orders/**

server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,gateway
  endpoint:
    health:
      show-details: always
