server:
  port: 8091

keycloak:
  auth-server-url: http://localhost:8081/auth
  realm: covidtest
  resource: shoppingcart-ms
  public-client: true
  principal-attribute: preferred_username
  bearer-only: true

spring:
  datasource:
    url: jdbc:h2:mem:shoppingcart-ms
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
